### PR TITLE
CLOUD-3228 openshift.KUBE_PING doesn't work on OCP 4.1 since it only …

### PR DESCRIPTION
**Pull request by rhusar**
…parses the first CA certificate from the ca.crt store

Jira
https://issues.jboss.org/browse/CLOUD-3228

### CODE REVIEW

**Review by luck3y — APPROVED** [review]

**Comment by luck3y** [comment]
@errantepiphany Can you take a look at this? This is required for OS 4.1 openshift.KUBE_PING to work.

If it looks ok to you, how many beers do I need to buy you to get you to do a release? :)

**Comment by errantepiphany** [comment]
@luck3y  Hi Ken. It looks good to me. It doesn't look like there is a test for it, though. But... I don't think there was a test for it to begin with. Have you been able to manually test successfully?

**Comment by luck3y** [comment]
@errantepiphany Yeah, I built a test image and tested that (QE is testing with it too.) @rhusar did his own testing as well.

**Comment by errantepiphany** [comment]
@luck3y Okay I'll merge, tag, and create a new brew build for you. Is there anything else I should wait for? Or is it just this one change?

**Review by errantepiphany — APPROVED** [review]

**Pull request merged**
