### PR TITLE
[CLOUD-700] Fixed NPE

### PR DESCRIPTION
**Pull request by douglaspalmer**

### CODE REVIEW

**Comment by slaskawi** [comment]
PR Moved to the new upstream repo: https://github.com/jgroups-extras/jgroups-kubernetes/pull/10

**Comment by slaskawi** [comment]
Hey @douglaspalmer ! I created a new repository for "upstream" version of KUBE_PING here: https://github.com/jgroups-extras/jgroups-kubernetes

**Comment by slaskawi** [comment]
I checked it once again - this PR integrates nicely into the master branch.

**Comment by rcernich** [comment]
rebased and merged

**Pull request closed without merging**
