### PR TITLE
Cloud 1509/fix false sharing between tests

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/CLOUD-1509

### CODE REVIEW

**Comment by luksa** [comment]
LGTM

**Comment by rcernich** [comment]
Hey @slaskawi, do you mind squashing these together?  I'll push it and roll the version so we can get an official build going.  Thanks @luksa for finding the root cause of the issue.

**Comment by luksa** [comment]
@slaskawi found it at the same time, actually :).

**Comment by slaskawi** [comment]
@rcernich Done. BTW, you can always use rebase & squash option on the PR :)

**Comment by rcernich** [comment]
thanks guys!

**Pull request merged**
